import Head from 'next/head';
import { SimpleGrid, useColorModeValue, Icon, Spacer} from '@chakra-ui/react';
import {
  MdAttachMoney,
  MdBarChart
} from 'react-icons/md';
import { GiFertilizerBag } from "react-icons/gi";
import { BsCloudRainFill } from "react-icons/bs";
import { TbClockHour3 } from "react-icons/tb";
import IconBox from '@/components/icons/IconBox';
import dynamic from 'next/dynamic'

// Custom Components
import FilterComponent from "@/components/headerfilter/FilterComponent";
import Navbar from '@/components/navbar/nav';
import TemperatureComponent from '@/components/Temperature';
import HumidityComponent from '@/components/Humidity'; 
import Tasks from '@/views/admin/default/components/Tasks';
import ComplexTable from '@/views/admin/default/components/ComplexTable';
import tableDataComplex from '@/views/admin/default/variables/tableDataComplex';
import DrawerComponent from '@/components/drawer/Drawer'
import MiniStatistics from '@/components/card/MiniStatistics';
import ScatterPlot from '@/components/WeightvsLocation';
import AdminLayout from '@/layouts/admin';

const DynamicMap = dynamic(() => import('../components/map/RobotMap'), {
  ssr: false
});

export default function Home() {

  const brandColor = useColorModeValue('brand.500', 'white');
  const boxBg = useColorModeValue('secondaryGray.300', 'whiteAlpha.100');

  return (
    <AdminLayout>
   <div>
      <Head>
        <title>Adam App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <FilterComponent />
      <div className=''>
      <DrawerComponent />
      </div>
     <Spacer className='p-12 mt-5'/>
      <SimpleGrid
           columns={{ base: 1, md: 2, lg: 3, '2xl': 6 }}
           gap="20px"
           mb="20px"
         >
           <MiniStatistics
             startContent={
               <IconBox
                 w="56px"
                 h="56px"
                 bg={boxBg}
                 icon={
                   <Icon w="32px" h="32px" as={BsCloudRainFill} color={brandColor} />
                 }
               />
             }
             name="Cumulative Rainfall"
             value="113mm"
           />
           <MiniStatistics
             startContent={
               <IconBox
                 w="56px"
                 h="56px"
                 bg={boxBg}
                 icon={
                   <Icon w="32px" h="32px" as={GiFertilizerBag} color={brandColor} />
                 }
               />
             }
             name="Fertilizer Requirement"
             value="50 litres/day"
           />
           <MiniStatistics growth="+23%" name="Agriculture Sprayed" value="22 hectare" />
           <MiniStatistics
          startContent={
            <IconBox
              w="56px"
              h="56px"
              bg={boxBg}
              icon={
                <Icon w="32px" h="32px" as={MdBarChart} color={brandColor} />
              }
            />
          }
          name="Earnings"
          value="$350.4"
        />
        <MiniStatistics
          startContent={
            <IconBox
              w="56px"
              h="56px"
              bg={boxBg}
              icon={
                <Icon w="32px" h="32px" as={MdAttachMoney} color={brandColor} />
              }
            />
          }
          name="Spend this month"
          value="$642.39"
        />
        <MiniStatistics
          startContent={
            <IconBox
              w="56px"
              h="56px"
              bg={boxBg}
              icon={
                <Icon w="32px" h="32px" as={TbClockHour3} color={brandColor} />
              }
            />
          }
          name="Total Hours Invested"
          value="2935"
        />
         </SimpleGrid>
         <SimpleGrid columns={{ base: 1, md: 2, xl: 2 }} gap="20px" mt="20px" mb="20px">
        <DynamicMap />
        <ScatterPlot />
      </SimpleGrid>
      <SimpleGrid columns={{ base: 1, md: 2, xl: 2 }} gap="20px" mb="20px">
      <TemperatureComponent />
      <HumidityComponent />
      </SimpleGrid>
      <SimpleGrid columns={{ base: 1, md: 1, xl: 2 }} gap="20px" mb="20px">
      <ComplexTable tableData={tableDataComplex} />
       <Tasks />
      </SimpleGrid>
   </div>
   </AdminLayout>
  );
}
